extends GogaGame
## Fruit Slasher - v0.2.9, REBUILT FROM THE RIND OUT (the owner: "currently
## it's too bad, even my PGB v1.3.8 is bad so you have nothing as
## reference"). The owner's contract:
##   - it STARTS with the position ask (like snake), each position with
##     its own physics: PORTRAIT tosses fruit up from below (classic),
##     LANDSCAPE lobs it across from the left with flatter, faster arcs
##   - a better background with cool minimal effects (dusk gradient, slow
##     light rays, drifting bokeh)
##   - slashing = real Slicing: the fruit is cut AT the slash segment and
##     SPLITS into two textured halves (polygon clipping against the cut
##     line) that fly apart with physical flips; a glowing blade ribbon,
##     per-fruit juice VFX, per-fruit wet SFX
##   - each fruit = +1; each fruit that FELL unsliced = -2 (score floors
##     at 0); hearts: 3 - slashing a bomb takes one, 0 hearts ends the run
##   - NO combos: a cool +N / -N visualizer instead - one slash counting
##     +1 +2 +3 in one top zone, falls flushing as one -N beside it
##   - spawner: patterns (single / pair / fan / ROW with a sneaky bomb
##     tucked between fruits), speeds that grow with the clock
##   - a GOGACoin every 20s from the last one, tossed like a fruit,
##     collected by slashing it
##   - the shop sells VEGETABLES (1500): once bought, the options screen
##     carries a FRUITS / VEGETABLES toggle
##   - run bonus /15 (registry coin_div 15)
##
## Probe contract: board state (items/halves/hearts/score) is public;
## _spawn_pattern/_cut_item/_register_cut/_flush_loss drive the laws
## headless; MODES is a const.

const MODES := {
        "vertical": {
                "title": "PORTRAIT",
                "gravity": 1560.0,
                "from_bottom": true,
                "vx": [-140.0, 140.0],
                "vy": [-1580.0, -1200.0],
                "spin": [-3.2, 3.2],
        },
        "horizontal": {
                "title": "LANDSCAPE",
                "gravity": 1180.0,
                "from_bottom": false,
                "vx": [640.0, 1020.0],
                "vy": [-540.0, -120.0],
                "spin": [-4.6, 4.6],
        },
}
const MISS_COST := 2               # owner: a fallen fruit costs -2
const START_HEARTS := 3
const COIN_EVERY_S := 20.0         # owner: one coin each 20s from the last
const SLICE_HALF_V := 210.0        # the halves' split impulse
const VEG_PRICE := 1500
const LOSS_WINDOW := 0.9           # falls inside this window flush as one -N

const FRUITS := ["watermelon", "orange", "apple", "lemon", "pear",
        "strawberry", "peach", "plum"]
const VEGGIES := ["carrot", "tomato", "eggplant", "broccoli", "corn", "pepper"]
## the juice tints per piece (generated by tools/v029_fruits.py JUICE)
const JUICE := {
        "watermelon": Color("ff5c6d"), "orange": Color("ff9f43"),
        "apple": Color("ff6b6b"), "lemon": Color("fff176"),
        "pear": Color("d4e157"), "strawberry": Color("ff4081"),
        "peach": Color("ffab91"), "plum": Color("ba68c8"),
        "carrot": Color("ff9e40"), "tomato": Color("ff5252"),
        "eggplant": Color("eceff1"), "broccoli": Color("9ccc65"),
        "corn": Color("ffe082"), "pepper": Color("aedd83"),
}

# ---------------------------------------------------------------- state
var _phase := "orient"             # orient -> options -> run
var orient := "vertical"
var items: Array = []              # whole flying things {node, kind, tex, v, spin, sliced, scale}
var halves: Array = []             # cut halves {node, v, spin, life, max}
var drops: Array = []              # juice droplets {node, v, life, max}
var flashes: Array = []            # slash flashes {a, b, life, max, col}
var hearts := START_HEARTS
var clock := 0.0
var spawn_clock := 0.9
var coin_clock := COIN_EVERY_S
var mode_id := "fruits"            # fruits | veggies (the shop toggle)
var slashed_total := 0
var missed_total := 0

# the +N / -N visualizer (the owner: "not spam and not weak")
var swipe_gain := 0                # cuts in the CURRENT swipe
var loss_acc := 0                  # falls waiting to flush as one -N
var loss_flush := 0.0
var viz: Array = []                # {txt, col, life, max, zone, pop}

# scene
var world: Node2D
var bg_painter: Node2D
var trail_painter: Node2D
var viz_painter: Node2D
var hearts_row: HBoxContainer
var heart_icons: Array = []
var trail: Array = []              # blade ribbon points {x, y, age}
var cut_flash: Array = []
var _shake := 0.0
var _time := 0.0
var _texs := {}                    # kind -> Texture2D
var _bomb_tex: Texture2D
var _coin_tex: Texture2D
var _heart_tex: Texture2D
var _rng := RandomNumberGenerator.new()
var _miss_sfx_clock := 0.0
var _over := false

# ============================================================ setup / flow

func _goga_setup() -> void:
        _rng.randomize()
        tk.dragged.connect(_on_drag)
        tk.press_started.connect(func(_p): swipe_gain = 0)
        tk.press_ended.connect(func(_p): _flush_gain())
        _load_textures()
        var forced := start_orientation
        if forced != "":
                orient = forced
                _build_world()
                _show_options()      # the ask is behind us (reload path)
        else:
                _build_world()
                _show_orient_select()

func _load_textures() -> void:
        for k in FRUITS:
                _texs[k] = load("res://assets/games/slasher/f_%s.png" % k)
        for k in VEGGIES:
                _texs[k] = load("res://assets/games/slasher/v_%s.png" % k)
        _bomb_tex = load("res://assets/games/slasher/bomb.png")
        _coin_tex = load("res://assets/ui/coin.png")
        _heart_tex = load("res://assets/ui/heart.png")

func _auto_landscape() -> bool:
        var vp := get_viewport_rect().size
        return vp.x > vp.y

func orientation_settled() -> void:
        if _phase == "orient":
                orient = "horizontal" if _auto_landscape() else "vertical"
                _show_options()

## THE TAP LAW (the snake's): the live window decides
func _orient_choice(choice: String) -> void:
        Jukebox.sfx("confirm", -4.0)
        Box.set_progress(game_id, "orient_pref", choice)
        if choice == ("horizontal" if _auto_landscape() else "vertical"):
                orient = choice
                _show_options()
        else:
                request_orientation_reload.emit(choice)

func _clear_overlay() -> void:
        for n in _overlay_root_ref().get_children():
                n.queue_free()

func _dim_layer() -> ColorRect:
        var dim := ColorRect.new()
        dim.color = Color(0.03, 0.05, 0.07, 0.72)
        dim.set_anchors_preset(Control.PRESET_FULL_RECT)
        dim.mouse_filter = Control.MOUSE_FILTER_STOP
        _overlay_root_ref().add_child(dim)
        return dim

func _center_in(dim: Control) -> CenterContainer:
        var cc := CenterContainer.new()
        cc.set_anchors_preset(Control.PRESET_FULL_RECT)
        cc.mouse_filter = Control.MOUSE_FILTER_IGNORE
        dim.add_child(cc)
        return cc

func _phone_card(kind: String, selected: bool) -> Button:
        var b := Button.new()
        b.custom_minimum_size = Vector2(250, 300)
        var sb := Arc.panel_style(Arc.ACCENT if selected else Arc.CARD, 22, 12)
        if not selected:
                sb.set_border_width_all(3)
                sb.border_color = Color(0, 0, 0, 0.12)
        b.add_theme_stylebox_override("normal", sb)
        var sbp := sb.duplicate() as StyleBoxFlat
        sbp.bg_color = sbp.bg_color.darkened(0.06)
        b.add_theme_stylebox_override("pressed", sbp)
        var vb := VBoxContainer.new()
        vb.set_anchors_preset(Control.PRESET_FULL_RECT)
        vb.alignment = BoxContainer.ALIGNMENT_CENTER
        vb.add_theme_constant_override("separation", 10)
        vb.mouse_filter = Control.MOUSE_FILTER_IGNORE
        b.add_child(vb)
        var ic := TextureRect.new()
        ic.texture = load("res://assets/ui/phone_%s.png" % kind)
        ic.custom_minimum_size = Vector2(190, 190)
        ic.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
        ic.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
        ic.mouse_filter = Control.MOUSE_FILTER_IGNORE
        vb.add_child(ic)
        var l := Arc.label(("VERTICAL" if kind == "vertical" \
                        else "HORIZONTAL"), 17,
                        Arc.INK if not selected else Color(0.16, 0.10, 0.05))
        l.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
        l.mouse_filter = Control.MOUSE_FILTER_IGNORE
        vb.add_child(l)
        return b

## Screen 1: HOW DO YOU HOLD IT - each position is a different game
## (portrait tosses from below, landscape lobs across from the left)
func _show_orient_select() -> void:
        _phase = "orient"
        _clear_overlay()
        var dim := _dim_layer()
        var cc := _center_in(dim)
        var panel := PanelContainer.new()
        panel.add_theme_stylebox_override("panel",
                        Arc.panel_style(Color(1, 1, 1, 0.96), 26, 24))
        cc.add_child(panel)
        var row := HBoxContainer.new()
        row.add_theme_constant_override("separation", 18)
        row.alignment = BoxContainer.ALIGNMENT_CENTER
        panel.add_child(row)
        var cur := "horizontal" if _auto_landscape() else "vertical"
        for choice in ["vertical", "horizontal"]:
                var card := _phone_card(choice, choice == cur)
                card.pressed.connect(func(): _orient_choice(choice))
                row.add_child(card)
        # the hint lives INSIDE the panel (a CenterContainer would stack
        # it ON the cards)
        var hint := Arc.fit_label("each position throws its fruit differently",
                        16, Arc.HOT, 520)
        hint.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
        hint.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
        panel.add_child(hint)

## Screen 2: the options - the produce toggle (vegetables need buying)
## and the START. The owner: "once bought let it in the optionals menu
## where it has a toggle for the type".
func _show_options() -> void:
        _phase = "options"
        _clear_overlay()
        var dim := _dim_layer()
        var cc := _center_in(dim)
        var panel := PanelContainer.new()
        panel.add_theme_stylebox_override("panel",
                        Arc.panel_style(Color(1, 1, 1, 0.97), 26, 24))
        cc.add_child(panel)
        var box := VBoxContainer.new()
        box.add_theme_constant_override("separation", 14)
        panel.add_child(box)
        var title := Arc.label("FRUIT SLASHER", 40, Arc.INK)
        title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
        box.add_child(title)
        # the produce toggle
        var owned := Box.item_owned(game_id, "produce", "veggies") \
                        or int(Box.dev_cheat("all_owned")) > 0
        mode_id = Box.item_on(game_id, "produce")
        if mode_id != "veggies":
                mode_id = "fruits"
        if owned:
                var row := HBoxContainer.new()
                row.add_theme_constant_override("separation", 10)
                row.alignment = BoxContainer.ALIGNMENT_CENTER
                box.add_child(row)
                var lf := Arc.button("FRUITS", Vector2(200, 70), 22,
                                Arc.GOOD if mode_id == "fruits" else Arc.CARD,
                                func():
                                        mode_id = "fruits"
                                        Box.equip_item(game_id, "produce", "fruits")
                                        Jukebox.sfx("confirm", -4.0)
                                        _show_options())
                row.add_child(lf)
                var lv := Arc.button("VEGETABLES", Vector2(240, 70), 22,
                                Arc.GOOD if mode_id == "veggies" else Arc.CARD,
                                func():
                                        mode_id = "veggies"
                                        Box.equip_item(game_id, "produce", "veggies")
                                        Jukebox.sfx("confirm", -4.0)
                                        _show_options())
                row.add_child(lv)
        else:
                var desc := Arc.fit_label("the vegetable basket is a shop "
                                + "item - one purchase, yours forever", 18,
                                Arc.HOT, 520)
                desc.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
                box.add_child(desc)
                var buy := Arc.coin_button("BUY THE VEGETABLES  %d" % VEG_PRICE,
                                Vector2(520, 74), 22, Color("4a5ab8"), func():
                                        if Box.buy_item(game_id, "produce",
                                                        "veggies", VEG_PRICE):
                                                Jukebox.sfx("buy")
                                                mode_id = "veggies"
                                                Box.equip_item(game_id,
                                                        "produce", "veggies")
                                        _show_options())
                if Box.coins() < VEG_PRICE and not int(Box.dev_cheat("all_owned")) > 0:
                        buy.disabled = true
                var bc := HBoxContainer.new()
                bc.alignment = BoxContainer.ALIGNMENT_CENTER
                bc.add_child(buy)
                box.add_child(bc)
        var start := Arc.button("START", Vector2(520, 88), 30, Arc.GOOD,
                        func(): _start_run())
        var sc := HBoxContainer.new()
        sc.alignment = BoxContainer.ALIGNMENT_CENTER
        sc.add_child(start)
        box.add_child(sc)

func _start_run() -> void:
        Jukebox.sfx("confirm", -4.0)
        _clear_overlay()
        _phase = "run"
        _build_hearts()
        spawn_clock = 0.7
        coin_clock = COIN_EVERY_S
        Jukebox.sfx("sl_launch", -8.0)

# ============================================================ the world

func _build_world() -> void:
        if world != null and is_instance_valid(world):
                world.queue_free()
        world = Node2D.new()
        add_child(world)
        bg_painter = Node2D.new()
        bg_painter.z_index = -10
        bg_painter.draw.connect(_paint_bg)
        world.add_child(bg_painter)
        trail_painter = Node2D.new()
        trail_painter.z_index = 30
        trail_painter.draw.connect(_paint_trail)
        world.add_child(trail_painter)
        viz_painter = Node2D.new()
        viz_painter.z_index = 40
        viz_painter.draw.connect(_paint_viz)
        world.add_child(viz_painter)

func _build_hearts() -> void:
        hearts_row = HBoxContainer.new()
        hearts_row.set_anchors_preset(Control.PRESET_TOP_WIDE)
        hearts_row.offset_left = 14
        hearts_row.offset_top = 86
        hearts_row.offset_right = -14
        hearts_row.add_theme_constant_override("separation", 6)
        _hud.add_child(hearts_row)
        for i in START_HEARTS:
                var h := TextureRect.new()
                h.texture = _heart_tex
                h.custom_minimum_size = Vector2(40, 40)
                h.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
                h.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
                h.mouse_filter = Control.MOUSE_FILTER_IGNORE
                hearts_row.add_child(h)
                heart_icons.append(h)
        _refresh_hearts()

func _refresh_hearts() -> void:
        for i in heart_icons.size():
                var h: TextureRect = heart_icons[i]
                h.modulate = Color(0.95, 0.2, 0.25) if i < hearts \
                                else Color(0.16, 0.12, 0.12, 0.6)

# ============================================================ the painter

func _paint_bg() -> void:
        var vp := get_viewport_rect().size
        # the dusk gradient (deep teal -> warm dark)
        var pts := PackedVector2Array([Vector2(0, 0), Vector2(vp.x, 0),
                        Vector2(vp.x, vp.y), Vector2(0, vp.y)])
        var cols := PackedColorArray([Color("17323f"), Color("17323f"),
                        Color("1d1a26"), Color("1d1a26")])
        bg_painter.draw_polygon(pts, cols)
        # the slow light rays (three, drifting)
        for r in 3:
                var sw := vp.x * (0.16 + 0.06 * r)
                var x := fposmod(_time * (7.0 + 3.0 * r) + r * vp.x * 0.42,
                                vp.x + sw) - sw
                var ray := PackedVector2Array([
                                Vector2(x, -20), Vector2(x + sw, -20),
                                Vector2(x + sw * 1.9 + vp.x * 0.1, vp.y + 20),
                                Vector2(x + sw * 0.7 + vp.x * 0.1, vp.y + 20)])
                bg_painter.draw_polygon(ray, PackedColorArray([
                                Color(1, 1, 1, 0.022), Color(1, 1, 1, 0.03),
                                Color(1, 1, 1, 0.0), Color(1, 1, 1, 0.0)]))
        # the drifting bokeh
        for i in 9:
                var ph := float(i) * 2.399
                var bx: float = fposmod(ph * 97.0, vp.x)
                var by: float = fposmod(vp.y - _time * (11.0 + 4.0 * (i % 4))
                                - ph * 60.0, vp.y + 80.0) - 40.0
                var rr := 5.0 + 12.0 * (float(i % 3) / 2.0)
                bg_painter.draw_circle(Vector2(bx, by), rr,
                                Color(1.0, 1.0, 0.9, 0.035 + 0.012 * float(i % 3)))
        # the soft floor shade (where the fruit is born)
        var floor_h := 90.0
        var fp := PackedVector2Array([Vector2(0, vp.y - floor_h),
                        Vector2(vp.x, vp.y - floor_h),
                        Vector2(vp.x, vp.y), Vector2(0, vp.y)])
        bg_painter.draw_polygon(fp, PackedColorArray([
                        Color(0, 0, 0, 0.0), Color(0, 0, 0, 0.0),
                        Color(0, 0, 0, 0.30), Color(0, 0, 0, 0.30)]))

func _paint_trail() -> void:
        # THE BLADE RIBBON: a tapered strip - white core, pale glow
        if trail.size() >= 2:
                for pass_i in 2:
                        var w := 26.0 if pass_i == 0 else 9.0
                        var col := Color(0.65, 0.9, 1.0, 0.30) if pass_i == 0 \
                                        else Color(1, 1, 1, 0.92)
                        for i in range(1, trail.size()):
                                var p0: Dictionary = trail[i - 1]
                                var p1: Dictionary = trail[i]
                                var f0: float = clampf(1.0 - float(p0["age"]) / 0.30, 0.0, 1.0)
                                var f1: float = clampf(1.0 - float(p1["age"]) / 0.30, 0.0, 1.0)
                                var a: Vector2 = p0["pos"]
                                var b: Vector2 = p1["pos"]
                                var dir := (b - a).normalized()
                                if dir == Vector2.ZERO:
                                        continue
                                var perp := Vector2(-dir.y, dir.x)
                                var quad := PackedVector2Array([
                                                a + perp * w * 0.5 * f0,
                                                b + perp * w * 0.5 * f1,
                                                b - perp * w * 0.5 * f1,
                                                a - perp * w * 0.5 * f0])
                                var cc := col
                                cc.a *= minf(f0, f1)
                                trail_painter.draw_polygon(quad,
                                                PackedColorArray([cc, cc, cc, cc]))
        # the cut flashes (bright lines along every fresh slash)
        for f in flashes:
                var t: float = clampf(float(f["life"]) / float(f["max"]), 0.0, 1.0)
                var c: Color = f["col"]
                c.a = t * 0.85
                trail_painter.draw_line(f["a"], f["b"], c, 7.0 * t + 1.0)

func _paint_viz() -> void:
        # the +N / -N zones (the owner: "one area maybe at the top... and
        # another one next to it for the -nn")
        var vp := get_viewport_rect().size
        var font := ThemeDB.fallback_font
        for v in viz:
                var t: float = clampf(float(v["life"]) / float(v["max"]), 0.0, 1.0)
                var pop: float = 1.0 + 0.45 * float(v["pop"])
                var zx: float = vp.x * (0.36 if int(v["zone"]) == 0 else 0.64)
                var zy: float = 128.0 + float(v["stack"]) * 44.0
                var c: Color = v["col"]
                c.a = minf(1.0, t * 1.6)
                var txt := String(v["txt"])
                var fs := int(38.0 * pop)
                viz_painter.draw_set_transform(Vector2(zx, zy), 0.0,
                                Vector2(pop, pop))
                viz_painter.draw_string_outline(font, Vector2(-60, 14), txt,
                                HORIZONTAL_ALIGNMENT_CENTER, 120, fs, 6,
                                Color(0, 0, 0, c.a * 0.8))
                viz_painter.draw_string(font, Vector2(-60, 14), txt,
                                HORIZONTAL_ALIGNMENT_CENTER, 120, fs, c)
                viz_painter.draw_set_transform(Vector2.ZERO, 0.0, Vector2.ONE)

# ============================================================ the spawn

func _item_kind() -> String:
        var pool: Array = FRUITS if mode_id == "fruits" else VEGGIES
        return String(pool[_rng.randi() % pool.size()])

func _item_scale(kind: String) -> float:
        if kind == "coin":
                return 0.34
        if kind == "bomb":
                return 0.62
        return _rng.randf_range(0.44, 0.58)

## one flying thing, born per the MODE (the position law: portrait tosses
## from below, landscape lobs across from the left)
func _launch(kind: String, at: Vector2 = Vector2.INF,
                speed := 1.0) -> void:
        var vp := get_viewport_rect().size
        var m: Dictionary = MODES[orient]
        var s := Sprite2D.new()
        if kind == "bomb":
                s.texture = _bomb_tex
        elif kind == "coin":
                s.texture = _coin_tex
        else:
                s.texture = _texs[kind]
        var pos := at
        var v := Vector2.ZERO
        if bool(m["from_bottom"]):
                if pos == Vector2.INF:
                        pos = Vector2(_rng.randf_range(vp.x * 0.14, vp.x * 0.86),
                                        vp.y + 70.0)
                v = Vector2(_rng.randf_range(m["vx"][0], m["vx"][1]),
                                _rng.randf_range(m["vy"][0], m["vy"][1]) * speed)
        else:
                if pos == Vector2.INF:
                        pos = Vector2(-70.0, _rng.randf_range(vp.y * 0.16,
                                        vp.y * 0.74))
                v = Vector2(_rng.randf_range(m["vx"][0], m["vx"][1]) * speed,
                                _rng.randf_range(m["vy"][0], m["vy"][1]))
        s.position = pos
        var sc := _item_scale(kind)
        s.scale = Vector2.ONE * sc
        s.rotation = _rng.randf_range(0.0, TAU)
        world.add_child(s)
        items.append({
                "node": s, "kind": kind, "v": v,
                "spin": _rng.randf_range(m["spin"][0], m["spin"][1]),
                "sliced": false, "scale": sc,
                "g": float(m["gravity"]),
        })
        if _rng.randf() < 0.5:
                Jukebox.sfx("sl_launch", -16.0, _rng.randf_range(0.9, 1.1))

## THE SPAWN PATTERNS (the owner: "different ways... harder and easier...
## different speeds... some bombs sneaky between a row of fruits")
func _spawn_pattern() -> void:
        var speed := 0.92 + minf(0.5, clock / 90.0) + _rng.randf_range(-0.12, 0.16)
        if _rng.randf() < 0.08:
                speed *= 1.28                  # the occasional fast one
        var roll := _rng.randf()
        if roll < 0.38:
                _launch(_roll_kind(0.12), Vector2.INF, speed)
        elif roll < 0.62:
                _launch(_roll_kind(0.12), Vector2.INF, speed)
                _launch(_roll_kind(0.12), Vector2.INF, speed * 0.94)
        elif roll < 0.78:
                # THE FAN: three from one point, spread
                var vp := get_viewport_rect().size
                var m: Dictionary = MODES[orient]
                var at := Vector2(_rng.randf_range(vp.x * 0.25, vp.x * 0.75),
                                vp.y + 60.0) if bool(m["from_bottom"]) \
                                else Vector2(-60.0, _rng.randf_range(
                                vp.y * 0.2, vp.y * 0.7))
                for i in 3:
                        _launch(_roll_kind(0.0), at, speed * (1.0 - 0.09 * i))
        else:
                # THE ROW: five in an arc - and a SNEAKY bomb tucked between
                # the fruits (the owner's ambush)
                var vp := get_viewport_rect().size
                var m: Dictionary = MODES[orient]
                var n := 5
                var bomb_i := _rng.randi() % n
                if bool(m["from_bottom"]):
                        var base_x := _rng.randf_range(vp.x * 0.2, vp.x * 0.8)
                        var base_vy := _rng.randf_range(m["vy"][0], m["vy"][1]) * 0.9
                        var base_vx := _rng.randf_range(-90.0, 90.0)
                        for i in n:
                                var kind := _roll_kind(0.0)
                                if i == bomb_i:
                                        kind = "bomb"
                                var at := Vector2(base_x + (i - n / 2.0)
                                                * (vp.x * 0.11), vp.y + 60.0)
                                _launch_at(kind, at, Vector2(base_vx,
                                                base_vy * _rng.randf_range(0.92, 1.08)))
                else:
                        # the LANDSCAPE row: a vertical curtain lobbed from
                        # the left - the bomb hides inside the arc
                        var base_y := _rng.randf_range(vp.y * 0.2, vp.y * 0.66)
                        var base_vx2 := _rng.randf_range(m["vx"][0], m["vx"][1]) * 0.9
                        var base_vy2 := _rng.randf_range(m["vy"][0], m["vy"][1])
                        for i in n:
                                var kind := _roll_kind(0.0)
                                if i == bomb_i:
                                        kind = "bomb"
                                var at := Vector2(-60.0, base_y + (i - n / 2.0)
                                                * (vp.y * 0.12))
                                _launch_at(kind, at, Vector2(
                                                base_vx2 * _rng.randf_range(0.92, 1.08),
                                                base_vy2))
        Jukebox.sfx("sl_launch", -14.0, _rng.randf_range(0.9, 1.15))

## a direct launch with an explicit velocity (rows)
func _launch_at(kind: String, at: Vector2, v: Vector2) -> void:
        var m: Dictionary = MODES[orient]
        var s := Sprite2D.new()
        if kind == "bomb":
                s.texture = _bomb_tex
        else:
                s.texture = _texs[kind]
        s.position = at
        var sc := _item_scale(kind)
        s.scale = Vector2.ONE * sc
        s.rotation = _rng.randf_range(0.0, TAU)
        world.add_child(s)
        items.append({"node": s, "kind": kind, "v": v,
                "spin": _rng.randf_range(m["spin"][0], m["spin"][1]),
                "sliced": false, "scale": sc, "g": float(m["gravity"])})

func _roll_kind(bomb_chance: float) -> String:
        if _rng.randf() < bomb_chance:
                return "bomb"
        return _item_kind()

# ============================================================ the tick

func _goga_tick(delta: float) -> void:
        _time += delta
        if _phase != "run":
                bg_painter.queue_redraw()
                return
        clock += delta
        # the spawner
        spawn_clock -= delta
        if spawn_clock <= 0.0:
                spawn_clock = maxf(0.78, 1.4 - clock * 0.009)
                _spawn_pattern()
        # the coin clock (owner: every 20s from the last APPEARED coin)
        coin_clock -= delta
        if coin_clock <= 0.0:
                coin_clock = COIN_EVERY_S
                _launch("coin")
        # the physics
        var vp := get_viewport_rect().size
        for p in items.duplicate():
                var n: Sprite2D = p["node"]
                var v: Vector2 = p["v"]
                v.y += float(p["g"]) * delta
                p["v"] = v
                n.position += v * delta
                n.rotation += float(p["spin"]) * delta
                if n.position.y > vp.y + 110.0 or n.position.x > vp.x + 130.0:
                        items.erase(p)
                        if String(p["kind"]) != "bomb" \
                                        and String(p["kind"]) != "coin" \
                                        and not bool(p["sliced"]):
                                _register_miss(n.position)
                        n.queue_free()
        # the halves fly and fade
        for h in halves.duplicate():
                var n: Node2D = h["node"]
                var v: Vector2 = h["v"]
                v.y += 1420.0 * delta
                h["v"] = v
                n.position += v * delta
                n.rotation += float(h["spin"]) * delta
                h["life"] = float(h["life"]) - delta
                if float(h["life"]) <= 0.0 or n.position.y > vp.y + 140.0:
                        halves.erase(h)
                        n.queue_free()
                elif float(h["life"]) < float(h["max"]) * 0.35:
                        n.modulate.a = float(h["life"]) / (float(h["max"]) * 0.35)
        # the juice drops (ColorRects - Controls carry position too)
        for d in drops.duplicate():
                var n: Node = d["node"]
                var v: Vector2 = d["v"]
                v.y += 1250.0 * delta
                d["v"] = v
                n.position += v * delta
                d["life"] = float(d["life"]) - delta
                n.modulate.a = clampf(float(d["life"]) / float(d["max"]), 0.0, 1.0)
                if float(d["life"]) <= 0.0:
                        drops.erase(d)
                        n.queue_free()
        # the trail ages
        for t in trail:
                t["age"] = float(t["age"]) + delta
        while trail.size() > 0 and float(trail[0]["age"]) > 0.30:
                trail.pop_front()
        for f in flashes.duplicate():
                f["life"] = float(f["life"]) - delta
                if float(f["life"]) <= 0.0:
                        flashes.erase(f)
        # the loss flush (falls inside the window flush as ONE -N)
        if loss_acc > 0:
                loss_flush -= delta
                if loss_flush <= 0.0:
                        _flush_loss()
        # the visualizer ages
        for v in viz.duplicate():
                v["life"] = float(v["life"]) - delta
                v["pop"] = maxf(0.0, float(v["pop"]) - delta * 5.0)
                if float(v["life"]) <= 0.0:
                        viz.erase(v)
        # the shake decays
        if _shake > 0.0:
                _shake = maxf(0.0, _shake - delta * 2.6)
                world.position = Vector2(_rng.randf_range(-1, 1),
                                _rng.randf_range(-1, 1)) * 14.0 * _shake
                if _shake == 0.0:
                        world.position = Vector2.ZERO
        _miss_sfx_clock = maxf(0.0, _miss_sfx_clock - delta)
        bg_painter.queue_redraw()
        trail_painter.queue_redraw()
        viz_painter.queue_redraw()

# ============================================================ the input

func _on_drag(from: Vector2, to: Vector2) -> void:
    if _phase != "run" or _over:
        return
    trail.append({"pos": to, "age": 0.0})
    if trail.size() > 26:
        trail.pop_front()
    var seg := to - from
    var speed := seg.length() / get_process_delta_time() if get_process_delta_time() > 0.0 else 0.0
    if seg.length() < 14.0 or speed < 500.0:
        return
    var hit := false
    for p in items.duplicate():
        var n: Sprite2D = p["node"]
        if bool(p["sliced"]):
            continue
        var d := _point_segment_dist(n.position, from, to)
        var hit_r := 46.0 * float(p["scale"]) / 0.5
        if d < hit_r:
            p["sliced"] = true
            items.erase(p)
            _cut_item(p, from, to)
            hit = true
    if hit:
        Jukebox.sfx("sl_whoosh", -10.0, _rng.randf_range(0.95, 1.1))

func _flush_gain() -> void:
    ## the swipe ended: the +N (one slash counting +1 +2 +3 in ONE zone)
    if swipe_gain <= 0:
        return
    _push_viz("+%d" % swipe_gain, Color(0.45, 0.95, 0.55), 0)
    swipe_gain = 0

func _register_miss(at: Vector2) -> void:
    ## a fruit fell unsliced: -2 (the score FLOORS at 0), accumulated so a
    ## burst of falls reads as one honest -N, never spam
    missed_total += 1
    if score > 0:
        set_score(maxi(0, score - MISS_COST))
    loss_acc += MISS_COST
    loss_flush = LOSS_WINDOW
    if _miss_sfx_clock <= 0.0:
        Jukebox.sfx("sl_miss", -8.0)
        _miss_sfx_clock = 0.2
    _puff(at, Color(0.8, 0.8, 0.8, 0.5))

func _flush_loss() -> void:
    if loss_acc <= 0:
        return
    _push_viz("-%d" % loss_acc, Color(0.98, 0.42, 0.36), 1)
    loss_acc = 0
    loss_flush = 0.0

func _push_viz(txt: String, col: Color, zone: int) -> void:
    ## the zones: 0 = gains (left), 1 = losses (right). A young entry in
    ## the same zone MERGES (the anti-spam law) with a fresh pop.
    for v in viz:
        if int(v["zone"]) == zone and float(v["life"]) > float(v["max"]) * 0.55:
            v["txt"] = txt
            v["life"] = 0.9
            v["max"] = 0.9
            v["pop"] = 1.0
            return
    # stack under existing entries in this zone
    var stack := 0
    for v in viz:
        if int(v["zone"]) == zone:
            stack += 1
    viz.append({"txt": txt, "col": col, "life": 0.9, "max": 0.9,
            "zone": zone, "pop": 1.0, "stack": stack})

# ============================================================ the cut

## THE REAL SLICE (the owner: "cut the fruit in that place and split it
## with physical flips"): clip the sprite's local square against the cut
## line, build two textured Polygon2D halves, throw them apart.
func _cut_item(p: Dictionary, from: Vector2, to: Vector2) -> void:
    items.erase(p)                        # safe for ANY caller
    var n: Sprite2D = p["node"]
    var kind := String(p["kind"])
    var tex: Texture2D = n.texture
    var sc: float = float(p["scale"])
    var juice: Color = JUICE.get(kind, Color("ffc93c"))
    # the flash along the cut
    flashes.append({"a": from, "b": to, "life": 0.14, "max": 0.14,
            "col": Color(1, 1, 1)})
    if kind == "coin":
        _coin_slashed(n.position)
        n.queue_free()
        return
    if kind == "bomb":
        _bomb_slashed(n.position)
        n.queue_free()
        return
    # the fruit: +1 and the halves
    add_score(1)
    swipe_gain += 1
    slashed_total += 1
    achievement_count("slashed", 1)
    # the wet voice (3 variants, pitched per fruit)
    var cut_names := ["sl_cut_a", "sl_cut_b", "sl_cut_c"]
    Jukebox.sfx(cut_names[_rng.randi() % 3], -4.0,
            _rng.randf_range(0.9, 1.18))
    # the local-space cut line (the slash segment mapped into the sprite)
    var local_a := _to_local(from, n, sc)
    var local_b := _to_local(to, n, sc)
    var dir := (local_b - local_a).normalized()
    if dir == Vector2.ZERO:
        dir = Vector2(1, 0)
    var nv := Vector2(-dir.y, dir.x)      # the split normal (local space)
    var line_off := nv.dot(local_a)       # nv . p = line_off
    var poly_a := _clip_square(nv, line_off, true)
    var poly_b := _clip_square(nv, line_off, false)
    var v: Vector2 = p["v"]
    var world_n: Vector2 = (n.global_transform.basis_xform(nv)).normalized()
    for i in 2:
        var poly: PackedVector2Array = poly_a if i == 0 else poly_b
        if poly.size() < 3:
            continue
        var half := Polygon2D.new()
        half.texture = tex
        var uv := PackedVector2Array()
        for pt in poly:
                uv.append((pt + Vector2(0.5, 0.5))
                        * Vector2(tex.get_width(), tex.get_height()))
        half.polygon = poly
        half.uv = uv
        half.position = n.position
        half.rotation = n.rotation
        half.scale = Vector2.ONE * sc * Vector2(tex.get_width(), tex.get_height()).x / 256.0
        # hmm: the polygon is in UNIT space; the scale must carry the
        # drawn size - the sprite drew tex at scale sc (px per unit =
        # sc * 256 since the art is 256px)
        world.add_child(half)
        var side := 1.0 if i == 0 else -1.0
        halves.append({
                "node": half,
                "v": v * 0.72 + world_n * (SLICE_HALF_V * side)
                                + Vector2(_rng.randf_range(-40, 40), -60.0),
                "spin": side * _rng.randf_range(3.0, 7.5),
                "life": _rng.randf_range(0.9, 1.25),
                "max": 1.25,
        })
    # THE JUICE: droplets + a splat ring, tinted by the fruit
    _splash(n.position, juice, dir_from_world(from, to))
    _splat_ring(n.position, juice)
    n.queue_free()

func dir_from_world(from: Vector2, to: Vector2) -> Vector2:
        return (to - from).normalized()

func _to_local(w: Vector2, n: Sprite2D, sc: float) -> Vector2:
        var t := n.global_transform.affine_inverse()
        var lp := t * w
        return lp / (sc * 256.0)   # into the unit square the polygon lives in

## Sutherland-Hodgman: clip the unit square by nv . p <= (>=) line_off
func _clip_square(nv: Vector2, line_off: float, keep_less: bool) -> PackedVector2Array:
        var square := [
                Vector2(-0.5, -0.5), Vector2(0.5, -0.5),
                Vector2(0.5, 0.5), Vector2(-0.5, 0.5),
        ]
        var out := PackedVector2Array()
        for i in 4:
                var a: Vector2 = square[i]
                var b: Vector2 = square[(i + 1) % 4]
                var da := (nv.dot(a) - line_off) * (1.0 if keep_less else -1.0)
                var db := (nv.dot(b) - line_off) * (1.0 if keep_less else -1.0)
                if da >= 0.0:
                        out.append(a)
                if (da >= 0.0) != (db >= 0.0):
                        var t := da / maxf(0.0001, da - db)
                        out.append(a.lerp(b, t))
        return out

func _coin_slashed(at: Vector2) -> void:
        add_run_coins(1)
        Jukebox.sfx("sl_coin_s", -3.0)
        _splash(at, Color("ffd24a"), Vector2.UP)
        _splat_ring(at, Color("ffd24a"))
        _push_viz("+COIN", Color("ffd24a"), 0)

func _bomb_slashed(at: Vector2) -> void:
        ## the owner's law: a slashed bomb takes ONE heart; 0 hearts ends
        hearts -= 1
        _refresh_hearts()
        _shake = 1.0
        Jukebox.sfx("sl_bomb", -2.0)
        _splash(at, Color("ffb347"), Vector2.UP, 26)
        flashes.append({"a": at + Vector2(-70, -70), "b": at + Vector2(70, 70),
                        "life": 0.2, "max": 0.2, "col": Color(1, 0.6, 0.2)})
        flashes.append({"a": at + Vector2(70, -70), "b": at + Vector2(-70, 70),
                        "life": 0.2, "max": 0.2, "col": Color(1, 0.6, 0.2)})
        if hearts <= 0:
                _run_over()
        else:
                Jukebox.sfx("sl_heart", -4.0)

func _run_over() -> void:
        if _over:
                return
        _over = true
        _phase = "over"
        Jukebox.sfx("sl_over", -2.0)
        achievement_max("hearts_kept", hearts)
        _flush_gain()
        _flush_loss()
        achievement_max("max_score", score)
        check_achievements()
        var tw := create_tween()
        tw.tween_property(world, "modulate", Color(0.7, 0.5, 0.5), 0.4)
        tw.tween_interval(0.5)
        tw.tween_callback(func(): finish_run(score))

# ============================================================ the vfx

func _splash(at: Vector2, col: Color, dir: Vector2, n := 12) -> void:
        ## the juice: droplets thrown against the cut direction, gravity
        ## pulls them down, they shrink and die
        for i in n:
                var d := ColorRect.new()
                var s := _rng.randf_range(5.0, 12.0)
                d.color = col
                d.size = Vector2(s, s * _rng.randf_range(0.7, 1.3))
                d.position = at + Vector2(_rng.randf_range(-14, 14),
                                _rng.randf_range(-14, 14))
                d.rotation = _rng.randf_range(0.0, TAU)
                d.z_index = 20
                d.mouse_filter = Control.MOUSE_FILTER_IGNORE
                world.add_child(d)
                var v := dir * _rng.randf_range(60.0, 240.0) \
                                + Vector2(_rng.randf_range(-160, 160),
                                _rng.randf_range(-260, 40))
                drops.append({"node": d, "v": v,
                                "life": _rng.randf_range(0.4, 0.8),
                                "max": 0.8})
        if drops.size() > 220:
                drops = drops.slice(drops.size() - 220)

func _splat_ring(at: Vector2, col: Color) -> void:
        ## the wet ring at the cut point (a quick expanding circle)
        var ring := Node2D.new()
        ring.position = at
        ring.z_index = 19
        var life := 0.28
        ring.draw.connect(func():
                var t: float = clampf(1.0 - ring.get_meta("l") / life, 0.0, 1.0)
                var c := col
                c.a = (1.0 - t) * 0.5
                ring.draw_arc(Vector2.ZERO, 14.0 + 44.0 * t, 0.0, TAU, 22, c, 5.0))
        ring.set_meta("l", life)
        world.add_child(ring)
        var tw := ring.create_tween()
        tw.tween_method(func(v: float): ring.set_meta("l", v),
                life, 0.0, life)
        tw.tween_callback(ring.queue_free)

func _puff(at: Vector2, col: Color) -> void:
        for i in 5:
                var d := ColorRect.new()
                var s := _rng.randf_range(4.0, 8.0)
                d.color = col
                d.size = Vector2(s, s)
                d.position = at
                d.z_index = 18
                d.mouse_filter = Control.MOUSE_FILTER_IGNORE
                world.add_child(d)
                var tw := d.create_tween().set_parallel(true)
                tw.tween_property(d, "position", at + Vector2(
                                _rng.randf_range(-40, 40),
                                _rng.randf_range(-10, 50)), 0.4)
                tw.tween_property(d, "modulate:a", 0.0, 0.4)
                tw.chain().tween_callback(d.queue_free)

# ============================================================ misc

func _point_segment_dist(pt: Vector2, a: Vector2, b: Vector2) -> float:
        var ab := b - a
        var t := clampf((pt - a).dot(ab) / maxf(0.001, ab.length_squared()),
                        0.0, 1.0)
        return pt.distance_to(a + ab * t)
